package com.solodev.ideahub.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2C5DAA)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF91B6FF)
val onPrimaryContainerLight = Color(0xFF00285B)
val secondaryLight = Color(0xFF4F5E7E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2DFFF)
val onSecondaryContainerLight = Color(0xFF364664)

// Adjusted tertiary colors to a cool teal
val tertiaryLight = Color(0xFF3D9CA8)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF94D2DF)
val onTertiaryContainerLight = Color(0xFF002A2E)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF1A1C21)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF1A1C21)
val surfaceVariantLight = Color(0xFFDFE2EF)
val onSurfaceVariantLight = Color(0xFF434751)
val outlineLight = Color(0xFF737782)
val outlineVariantLight = Color(0xFFC3C6D3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3036)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFACC7FF)

// Medium Contrast Colors
val primaryLightMediumContrast = Color(0xFF004189)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF4674C2)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF334361)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF657595)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF337E85)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6BC8D1)
val onTertiaryContainerLightMediumContrast = Color(0xFF001D20)

val primaryDark = Color(0xFFB7CEFF)
val onPrimaryDark = Color(0xFF002F67)
val primaryContainerDark = Color(0xFF79A5F6)
val onPrimaryContainerDark = Color(0xFF00193D)
val secondaryDark = Color(0xFFB7C7EB)
val onSecondaryDark = Color(0xFF21304D)
val secondaryContainerDark = Color(0xFF2E3D5B)
val onSecondaryContainerDark = Color(0xFFC1D1F5)

// Adjusted tertiary colors to a cool teal
val tertiaryDark = Color(0xFF63B9C1)
val onTertiaryDark = Color(0xFF002326)
val tertiaryContainerDark = Color(0xFF204F56)
val onTertiaryContainerDark = Color(0xFFA0E0E9)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF434751)
val onSurfaceVariantDark = Color(0xFFC3C6D3)
val outlineDark = Color(0xFF8D909C)
val outlineVariantDark = Color(0xFF434751)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val inversePrimaryDark = Color(0xFF2C5DAA)
