package com.solodev.ideahub.ui.theme
import androidx.compose.ui.graphics.Color
val primaryLight = Color(0xFF2C5DAA)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF91B6FF)
val onPrimaryContainerLight = Color(0xFF00285B)
val secondaryLight = Color(0xFF4F5E7E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2DFFF)
val onSecondaryContainerLight = Color(0xFF364664)
val tertiaryLight = Color(0xFF86458E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE69BEB)
val onTertiaryContainerLight = Color(0xFF490854)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF1A1C21)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF1A1C21)
val surfaceVariantLight = Color(0xFFDFE2EF)
val onSurfaceVariantLight = Color(0xFF434751)
val outlineLight = Color(0xFF737782)
val outlineVariantLight = Color(0xFFC3C6D3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3036)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFACC7FF)

val primaryLightMediumContrast = Color(0xFF004189)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF4674C2)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF334361)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF657595)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF672870)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9F5BA5)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9FF)
val onBackgroundLightMediumContrast = Color(0xFF1A1C21)
val surfaceLightMediumContrast = Color(0xFFF9F9FF)
val onSurfaceLightMediumContrast = Color(0xFF1A1C21)
val surfaceVariantLightMediumContrast = Color(0xFFDFE2EF)
val onSurfaceVariantLightMediumContrast = Color(0xFF3F434D)
val outlineLightMediumContrast = Color(0xFF5B5F6A)
val outlineVariantLightMediumContrast = Color(0xFF777A86)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E3036)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
val inversePrimaryLightMediumContrast = Color(0xFFACC7FF)


val primaryLightHighContrast = Color(0xFF00214C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004189)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF11223E)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF334361)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF40004B)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF672870)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9FF)
val onBackgroundLightHighContrast = Color(0xFF1A1C21)
val surfaceLightHighContrast = Color(0xFFF9F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE2EF)
val onSurfaceVariantLightHighContrast = Color(0xFF20242D)
val outlineLightHighContrast = Color(0xFF3F434D)
val outlineVariantLightHighContrast = Color(0xFF3F434D)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E3036)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE6ECFF)


val primaryDark = Color(0xFFB7CEFF)
val onPrimaryDark = Color(0xFF002F67)
val primaryContainerDark = Color(0xFF79A5F6)
val onPrimaryContainerDark = Color(0xFF00193D)
val secondaryDark = Color(0xFFB7C7EB)
val onSecondaryDark = Color(0xFF21304D)
val secondaryContainerDark = Color(0xFF2E3D5B)
val onSecondaryContainerDark = Color(0xFFC1D1F5)
val tertiaryDark = Color(0xFFFCB8FF)
val onTertiaryDark = Color(0xFF52135B)
val tertiaryContainerDark = Color(0xFFD58CDA)
val onTertiaryContainerDark = Color(0xFF35003E)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF434751)
val onSurfaceVariantDark = Color(0xFFC3C6D3)
val outlineDark = Color(0xFF8D909C)
val outlineVariantDark = Color(0xFF434751)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val inversePrimaryDark = Color(0xFF2C5DAA)

val primaryDarkMediumContrast = Color(0xFFB7CEFF)
val onPrimaryDarkMediumContrast = Color(0xFF00193C)
val primaryContainerDarkMediumContrast = Color(0xFF79A5F6)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFBBCBEF)
val onSecondaryDarkMediumContrast = Color(0xFF041631)
val secondaryContainerDarkMediumContrast = Color(0xFF8191B3)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFCB8FF)
val onTertiaryDarkMediumContrast = Color(0xFF34003D)
val tertiaryContainerDarkMediumContrast = Color(0xFFD58CDA)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF111318)
val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
val surfaceDarkMediumContrast = Color(0xFF111318)
val onSurfaceDarkMediumContrast = Color(0xFFFBFAFF)
val surfaceVariantDarkMediumContrast = Color(0xFF434751)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC7CAD7)
val outlineDarkMediumContrast = Color(0xFF9FA3AF)
val outlineVariantDarkMediumContrast = Color(0xFF7F838F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
val inversePrimaryDarkMediumContrast = Color(0xFF054691)

val primaryDarkHighContrast = Color(0xFFFBFAFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB2CBFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFBFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBBCBEF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFBB1FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF111318)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
val surfaceDarkHighContrast = Color(0xFF111318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF434751)
val onSurfaceVariantDarkHighContrast = Color(0xFFFBFAFF)
val outlineDarkHighContrast = Color(0xFFC7CAD7)
val outlineVariantDarkHighContrast = Color(0xFFC7CAD7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00295B)








val BluePrimary = Color(0xFF75A4FE) // Your primary color
val BlueSecondary = Color(0xFF1C3A7D) // Your secondary color
val BlueBackground = Color(0xFFC7E6F8) // Your background color
val White = Color(0xFFFFFFFF)
val GreyLight = Color(0xFFD3D3D3)
val GreyDark = Color(0xFF707070)




